use_frameworks!

platform :ios, '8.0'

target 'CTLogining_Example' do
  pod 'CTLogining', :path => '../'
  pod 'CTNetworking',path => '../../CTNetworking'
  
  
  target 'CTLogining_Tests' do
    inherit! :search_paths

    
  end
end
